// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvyUDdrL90cyuQUjb_uILyltQnEXv50m0',
    appId: '1:525749845350:web:d6c3435033e66de62e9ca7',
    messagingSenderId: '525749845350',
    projectId: 'siah-c8961',
    authDomain: 'siah-c8961.firebaseapp.com',
    storageBucket: 'siah-c8961.firebasestorage.app',
    measurementId: 'G-72L7GXZ8VP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpBB194rwDzLVXOheI88PRU0vH3c8Yvps',
    appId: '1:525749845350:android:71b87ee1756d5d622e9ca7',
    messagingSenderId: '525749845350',
    projectId: 'siah-c8961',
    storageBucket: 'siah-c8961.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxc7S3QW0xtEpElyHIAWbktqTowcfrZUU',
    appId: '1:525749845350:ios:c307a6dadd889e782e9ca7',
    messagingSenderId: '525749845350',
    projectId: 'siah-c8961',
    storageBucket: 'siah-c8961.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxc7S3QW0xtEpElyHIAWbktqTowcfrZUU',
    appId: '1:525749845350:ios:c307a6dadd889e782e9ca7',
    messagingSenderId: '525749845350',
    projectId: 'siah-c8961',
    storageBucket: 'siah-c8961.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvyUDdrL90cyuQUjb_uILyltQnEXv50m0',
    appId: '1:525749845350:web:b41b999e628cef412e9ca7',
    messagingSenderId: '525749845350',
    projectId: 'siah-c8961',
    authDomain: 'siah-c8961.firebaseapp.com',
    storageBucket: 'siah-c8961.firebasestorage.app',
    measurementId: 'G-PG1DPG6K6S',
  );
}
